# Generated by Django 3.0.8 on 2020-07-16 17:19

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_deadline', models.PositiveSmallIntegerField(default=14)),
                ('payment_method', models.CharField(default='przelew', max_length=50)),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
