# Generated by Django 3.0.8 on 2020-07-20 17:40

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='filename',
            field=models.CharField(max_length=100, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Issue date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_deadline',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='Payment deadline'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(default='przelew', max_length=50, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sale date'),
        ),
    ]
